### ISSUE TITLE
Feature Request : On/Off Button

### ISSUE THREAD

**Issue by JasonCarswell** [wizzwizz4/wikinotate#1]
I'd like a clearly visible on/off button.  When the app is installed and active this button should always be visible on every wiki that it works on - Wikipedia, WikiSpooks, InfoGalactic, RationalWiki, MetaWiki,  Wikia, Everipedia, Wiktionary, Wikimedia Commons, WikiVoyage, etc etc etc.

Ideally the on/off button might fit below the top-right wiki logo, just above "navigation".  If not there then further below in that left-hand margin, which is often empty space.

The active browser addon would always have the button visible.  When the addon is deactivated or uninstalled then it won't be visible.  When the active addon is operational it would be green and say "wikinotate: on" in white text and when the active addon is not operational it would be rust (red-brown) and say "wikinotate: off" in white text.  This distinctive design differentiates significantly from Wikipedia to make it clear and obvious there is more to the article viewing plus notation experience.  These colours may be carried through in other aspects of this app.

The on/off status may eventually require preferences.  For example:
* article notes by user shared publicly : on/off/default
* article notes by user private : on/off/default
* article notes shared by others : on/off/default
* watchlist article : on/off/default
* new "fresh" article : on/off/default
* keep custom history and preferences for visited pages : on/off/default

Obviously this likely requires databasing, public and private notations, watchlist referencing, some kind of history, etc.

**Comment by wizzwizz4** [comment]
This is hard, and it's nowhere near that stage yet.

**Comment by wizzwizz4** [comment]
wontfix
