### ISSUE TITLE
Feature Request : Security = Decentralized Databasing, Archiving, Blockchain Sharding, Rewards, Protocols, etc

### ISSUE THREAD

**Issue by JasonCarswell** [wizzwizz4/wikinotate#2]
I don't even know what this means practically, but in order to be free of the censored Wikipedia monopoly we need to be resilient to being censored, deleted, or taken down.

IMHO this requires some kind of decentralization implementation, and perhaps eventually some blockchain or sharding implementation.

Some sort of user identity and/or anonymity in databases will be necessary.

Rewards might be a nice incentive for those who contribute and for those who host the inevitably vast wealth of knowledge.

It may also be worthwhile building something resilient on several platforms simultaneously from the get go.  For example, this app may utilize several protocols and platforms, such as: Fediverse, Holochain, IPFS, WebTorrent, ZeroNet, etc.

Assuming this app has any success, "they" may eventually try to block it or limit users with it.  I don't know what to do about that, but it's fair to keep it in mind.

**Comment by wizzwizz4** [comment]
I don't know how the back-end is doing to work just yet. There's no way to make the system resistant to takedowns, but mirroring is pretty effective at making a system resilient. It'd be easy, but slow, to get it to go through an RSS feed or ActivityPub outbox or something, so a custom backend is probably required.

Literally anything that can provide something that can be turned into a series of JSON objects like [this](https://github.com/wizzwizz4/wikinotate/blob/138383cd8e8a767ffa76033e0f45213bd0421e18/inject.js#L39-L52) (format subject to change; is probably out of date at time of reading) would be usable. Even just an XML file would be OK.

Mastodon fork / plugin? I don't know!
