### ISSUE TITLE
Please test on Tampermonkey

### ISSUE THREAD

**Issue by JasonCarswell** [wizzwizz4/wikinotate#7]
Tampermonkey is similar to Greasemonkey.  Hopefully they work the same and there's never a problem.

The Chrome / Opera / Brave addon:
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
> The world's most popular userscript manager
> Tampermonkey is the most popular userscript manager, with over 10 million users.
> Tampermonkey is used to run so called userscripts (sometimes also called Greasemonkey scripts). Userscripts are little computer programs that for example add download buttons to YouTube pages, cleanup your Facebook timeline or help playing an online game.

Addon update page:
https://tampermonkey.net/index.php?version=4.8&ext=dhdg&updated=true

Feel free to let me/us know if there's a better addon.

If Tampermonkey is adequate perhaps link to it and Greasemonkey on the intro page.

Also, the intro page might benefit from a blurb for laymen about what the app does, future plans, and what resources are used.  Also, how the bookmarklets are stored and where.  And how to delete and uninstall.

Now I have to figure out how to work this and install WikiNotate.

**Comment by wizzwizz4** [comment]
For Greasemonkey it's just "install Greasemonkey, click link". Tampermonkey seems to provide no instructions for devs, so I can't work out how to make it compatible; it should already be.

The easiest way to "install" it while it's in development should be to use the bookmarklet; it's literally just a bookmark that "navigates to" WikiNotate when clicked.
